sudo: required
language: generic

services:
    - docker
cache:
    apt: true
    directories:
      - $HOME/docker
addons:
    apt:
        packages:
          - lzop

before_install:
  - export IMAGE=docker-test
  - export DOCKER_DIR=$HOME/docker
  - export APP_DIR=/app
install:
  - ./scripts/load-commit-image.sh

jobs:
    include:
      - stage: Build image
        install:
          - ./scripts/load-branch-image.sh
        script:
          - ./scripts/docker-build.sh
      - stage: Test and lint
        script: docker run $IMAGE:$TRAVIS_COMMIT /bin/sh -c "cd $APP_DIR; yarn test"
      - script: docker run $IMAGE:$TRAVIS_COMMIT /bin/sh -c "cd $APP_DIR; yarn lint"
