sudo: required

services:
    - docker

language: generic

cache:
    directories:
      - $HOME/docker

before_install:
  - export IMAGE=docker-test
  - export DOCKER_DIR=$HOME/docker
install:
  - gzip -dc $DOCKER_DIR/$IMAGE:$TRAVIS_COMMIT.tar.gz | docker load

jobs:
    include:
      - stage: Build image
        install:
          - if [[ -e $DOCKER_DIR/$IMAGE:$TRAVIS_BRANCH.tar.gz ]]; then gzip -dc $DOCKER_DIR/$IMAGE:$TRAVIS_BRANCH.tar.gz | docker load; fi
        script:
          - mkdir -p $DOCKER_DIR
          - docker build --rm=false --cache-from $IMAGE:$TRAVIS_BRANCH -t $IMAGE:$TRAVIS_COMMIT .
          - if [[ ! -e $DOCKER_DIR/$IMAGE:$TRAVIS_BRANCH.tar.gz ]]; then docker tag $IMAGE:$TRAVIS_COMMIT $IMAGE:$TRAVIS_BRANCH; docker save $IMAGE:$TRAVIS_BRANCH | gzip > $DOCKER_DIR/$IMAGE:$TRAVIS_BRANCH.tar.gz; fi
          - docker save $IMAGE:$TRAVIS_COMMIT | gzip > $DOCKER_DIR/$IMAGE:$TRAVIS_COMMIT.tar.gz
      - stage: Test and lint
        script: docker run $IMAGE:$TRAVIS_COMMIT /bin/sh -c "cd /root/docker-test; yarn test"
      - script: docker run $IMAGE:$TRAVIS_COMMIT /bin/sh -c "cd /root/docker-test; yarn lint"
