sudo: required

services:
    - docker

language: node_js
node_js: node

cache:
    directories:
      - $HOME/docker

before_install: docker load -i $HOME/docker/image.tar

jobs:
    include:
      - stage: Build image
        before_install: skip
        script:
          - docker build --rm=false -t jpreynat/docker-test .
          - mkdir -p $HOME/docker; docker save jpreynat/docker-test > $HOME/docker/image.tar
      - stage: Test and lint
        script: docker run jpreynat/docker-test /bin/sh -c "cd /root/docker-test; yarn test"
      - script: docker run jpreynat/docker-test /bin/sh -c "cd /root/docker-test; yarn lint"
