sudo: false
dist: trusty
language: node_js
node_js: 6.14.0

cache:
    apt: true
    yarn: true
    directories:
      - node_modules
      - $HOME/google-cloud-sdk
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
          - nasm

before_install:
  # Set envs
  - export CXX=g++-4.8
  - export PATH=$HOME/.yarn/bin:${HOME}/google-cloud-sdk/bin:$PATH
  # Install Google Cloud utils, the folder is created by travis since it's being cached
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  # Auth with Google Cloud utils
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0

jobs:
    include:
      - stage: Prepare
        script:
          - yarn --frozen-lockfile
      - stage: Test and lint
        script:
          - yarn test
      - script:
          - yarn lint
